---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: spin-merge-ns
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.6
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5775
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: trace
  namespace: spin-merge-ns
spec:
  selector:
    app: jaeger
  ports:
    - port: 16686
      targetPort: 16686
      name: web
    - port: 14268
      targetPort: 14268
      name: conn
