version: '0.1'
services:
  app:
    depends_on:
      - db
    image: rishavmehra/redis-python:latest
    networks:
      - back-tier

  db:
    image: redis:alpine
    command: 
    - sh
    - -c
    - 'redis-server'
    networks:
      - back-tier
    expose:
      - 6379


networks:
  back-tier:
