---
- name: PDF Editor playbook
  hosts: all
  become: true
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello from preview runner!!!

    - name: remove the running docker compose
      shell: "cd /home/ubuntu/SpinMergePro/IAC/ansible-terraform/ && docker-compose down && sleep 2"

    - name: removing the docker images
      shell: "docker rmi -f $(docker images -q) && docker volume prune -f"

    - name: run docker-compose again
      shell: "cd /home/ubuntu/SpinMergePro/IAC/ansible-terraform/ && sudo docker-compose up -d && curl --head -X GET http://localhost/"
