apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: spin-merge-ns
  labels:
    name: spin-merge-frontend
spec:
  selector:
    app: frontend-spin-merge
  type: ClusterIP
  ports:
    - port: 80
      name: web
      targetPort: web-port
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spin-merge-ig
  labels:
    name: spin-merge-ig
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: spin-merge-ns
spec:
  rules:
    - host: spin-merge
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: frontend-lb
                port:
                  number: 80
